### PR TITLE
extract buffer pool (and simplify interface)

### PR DESCRIPTION
**Pull request by Stebalien**
New go-buffer-pool repo: [libp2p/go-buffer-pool](https://github.com/libp2p/go-buffer-pool).

### CODE REVIEW

**Comment by kevina** [comment]
@Stebalien This is doing a bit more then just an extraction. Are there any others packages that use the the buffer pool from this package?

**Comment by Stebalien** [comment]
Yes and I will fix them as well. The interface just really sucked.

**Comment by kevina** [comment]
Okay, it is difficult for me to review this without seeing what changed in the buffer pool code.  I attempted to push tags to make a pull request out of the changes, but github is refusing, likely because the code is already in master.  At very least you can see the changes in go-buffer-pool from the extraction:

https://github.com/libp2p/go-buffer-pool/compare/pre-extract...master
https://github.com/libp2p/go-buffer-pool/compare/pre-extract...post-extract

Maybe if we reset master to pre-extract we can create a proper pull request for review...

**Comment by Stebalien** [comment]
> Okay, it is difficult for me to review this without seeing what changed in the buffer pool code. I attempted to push tags to make a pull request out of the changes, but github is refusing, likely because the code is already in master. 

I recommend you simply review it as new code. The new code is simpler than the old code.

If you actually want to see the diff, you can look at everything since 5ef65a036f9c5254313d3e123b3fe6c4b6bcad6e (`git diff 5ef65a036f9c5254313d3e123b3fe6c4b6bcad6e..master`).

(it's about 50 lines of actual code).

**Comment by Stebalien** [comment]
@bigs 

Can you take a look at this? I finally yoloed https://github.com/whyrusleeping/yamux/pull/5 so we now have two buffer pools (as that PR uses the buffer pool from the new go-buffer-pool package).

**Comment by Stebalien** [comment]
Blocked on:

* [x] https://github.com/ipfs/go-ipfs-chunker/pull/8
* [x] https://github.com/libp2p/go-libp2p-pnet/pull/24
* [x] https://github.com/libp2p/go-mplex/pull/31
* [x] https://github.com/libp2p/go-libp2p-secio/pull/30

**Review by bigs — APPROVED** [review]
lgtm!

**Pull request merged**
